name: Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'
    - name: Activate GO111MODULE
      run: export GO111MODULE="on"
      shell: bash
    - name: Install dependencies
      run: |
        go get .
        go get github.com/Greenlamp2/rogueserver/api
    - name: Build
      run: go build
    - name: Restart server
      run: sudo systemctl restart rogueserver.service
      shell: bash